<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <RootNamespace>Apizr</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>PixelSpark.Apizr.Extensions.Microsoft.DependencyInjection</PackageId>
    <Version>6.5.0</Version>
    <Authors>Respawnsive, PixelSpark</Authors>
    <Description>Fork of Apizr (https://github.com/Respawnsive/Apizr) retargeted to Refit 10.x and net10.0. Refit based web api client management, but resilient (retry, connectivity, cache, auth, log, priority...)</Description>
    <PackageProjectUrl>https://github.com/seansparkman/Apizr</PackageProjectUrl>
    <RepositoryUrl>https://github.com/seansparkman/Apizr</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageTags>Refit Polly Web Api Extensions</PackageTags>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>Apizr.Extensions.Microsoft.DependencyInjection.xml</DocumentationFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageReference Include="Refit.HttpClientFactory" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Apizr\Apizr.csproj" />
  </ItemGroup>
</Project>